after_vocabulary ={
  "On/in/at (location)": {"pinyin": "zài", "char": "在"},
  "On top": {"pinyin": "shàng miàn / shàng", "char": None},
  "Below": {"pinyin": "xià miàn / xià", "char": None},
  "Chair": {"pinyin": "yǐ zi", "char": None},
  "Cat": {"pinyin": "māo", "char": None},
  "Dog": {"pinyin": "gǒu", "char": None},
  "Fish": {"pinyin": "yú", "char": None},
  "Small": {"pinyin": "xiǎo", "char": None},
  "Kitty": {"pinyin": "xiǎo māo", "char": None},
  "Puppy": {"pinyin": "xiǎo gǒu", "char": None},
  "Big": {"pinyin": "dà", "char": None},
  "Elderly person": {"pinyin": "dà rén", "char": None},
  "Senior student": {"pinyin": "dà xué sheng", "char": None},
  "Primary school student": {"pinyin": "xiǎo xué sheng", "char": None},
  "Hospital": {"pinyin": "yī yuàn", "char": "医院"},
  "Doctor": {"pinyin": "yū sheng", "char": None},
  "Son": {"pinyin": "ér zi", "char": "儿子"},
  "To work": {"pinyin": "gōng zuò", "char": "工作"},
  "In front (direction)": {"pinyin": "qián miàn", "char": None},
  "Behind (direction)": {"pinyin": "hòu miàn", "char": None},
  "Before (time context)": {"pinyin": "qián", "char": None},
  "After (time context)": {"pinyin": "hòu", "char": None},
  "Inside (direction)": {"pinyin": "lǐ miàn", "char": "里面"},
  "Measure word for book": {"pinyin": "běn", "char": "本"},
  "Electricity": {"pinyin": "diàn", "char": "电"},
  "Brain": {"pinyin": "nǎo", "char": None},
  "Computer": {"pinyin": "diàn nǎo", "char": None},
  "Does not have / hasn't": {"pinyin": "méi yǒu", "char": None},
  "Excuse me": {"pinyin": "qǐng wèn", "char": None},
  "Please + action": {"pinyin": "qǐng + verb", "char": None},
  "Please sit": {"pinyin": "qǐng zuò", "char": None},
  "Sit down": {"pinyin": "zuò xià", "char": None},
  "Sit here": {"pinyin": "zuò zhèr", "char": None},
  "Sit in <direction>": {"pinyin": "zuò + direction", "char": None},
  "Do <action>": {"pinyin": "zuò + action", "char": None},
  "Sit where?": {"pinyin": "zuò nǎr", "char": None},
  "Can (permission/possibility)": {"pinyin": "néng", "char": None},
  "O'clock": {"pinyin": "diǎn", "char": "点"},
  "Minutes (w/ diǎn)": {"pinyin": "fēn", "char": "分"},
  "What time?": {"pinyin": "jǐ diǎn", "char": None},
  "Now": {"pinyin": "xiàn zài", "char": None},
  "Noon": {"pinyin": "zhōng wǔ", "char": None},
  "Afternoon": {"pinyin": "xià wǔ", "char": None},
  "Morning": {"pinyin": "shàng wǔ", "char": None},
  "To return": {"pinyin": "huí", "char": "回"},
  "Go back": {"pinyin": "huí qù", "char": None},
  "To look/read/watch": {"pinyin": "kàn", "char": None},
  "Shadow": {"pinyin": "yǐng", "char": None},
  "Movie": {"pinyin": "diǎn yǐng", "char": None},
  "Visit doctor": {"pinyin": "kàn yī sheng", "char": None},
  "Watch movie": {"pinyin": "kàn diǎn yǐng", "char": None},
  "Time": {"pinyin": "shí hou", "char": None},
  "What time?": {"pinyin": "shén me shí hou", "char": None},
  "To live / to stay": {"pinyin": "zhù", "char": "住"},
  "How is it? (condition/status)": {"pinyin": "zěn me yàng", "char": None},
  "Very (more extreme than hěn)": {"pinyin": "tài", "char": None},
  "Weather": {"pinyin": "tiān qì", "char": "天气"},
  "Cold": {"pinyin": "léng", "char": None},
  "Hot": {"pinyin": "rè", "char": None},
  "Miss": {"pinyin": "xiǎo jiě", "char": None},
  "Sister": {"pinyin": "jiě jiě", "char": None},
  "Elder sister": {"pinyin": "xiǎo jiě jiě", "char": None},
  "Younger sister": {"pinyin": "měi měi", "char": None},
  "To come": {"pinyin": "lái", "char": "来"},
  "Come back": {"pinyin": "lái qù", "char": None}
}
